### ISSUE TITLE
Top and bottom margins

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaquaclient#1]
I'm using `JTableWithMargins` for the inset style, but I'd like to have top and bottom margins as well—that seems to be what 🍎 does.

I have successfully experimented with changing `JTableWithMargins` to receive an `Insets` instead of an `Integer`, along with the corresponding change in VAqua. Are you on board with this approach? If so I can create PRs for it!

<img width="353" alt="image" src="https://user-images.githubusercontent.com/1086005/177294963-88f766d5-ccff-447e-a6a9-cfef7261c24b.png">

**Comment by cbfiddle** [comment]
Would an EmptyBorder(5, 0, 5, 0) work as well?

Side margins are special because they are part of the first and last column.

**Comment by cbfiddle** [comment]
Fixed in release 2.
